package main

import (
	"context"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	publicAddressDefault = ":8317"
	adminAddressDefault  = "127.0.0.1:8318"
	maxRequestBody       = 16 << 20
	sessionLifetime      = 12 * time.Hour
)

type config struct {
	DefaultModel string            `json:"defaultModel"`
	ModelAliases map[string]string `json:"modelAliases"`
	Accounts     []account         `json:"accounts"`
	CreatedAt    time.Time         `json:"createdAt"`
	UpdatedAt    time.Time         `json:"updatedAt"`
}

type account struct {
	ID              string    `json:"id"`
	Label           string    `json:"label"`
	Email           string    `json:"email,omitempty"`
	AuthType        string    `json:"authType"`
	Enabled         bool      `json:"enabled"`
	InPool          bool      `json:"inPool"`
	Priority        int       `json:"priority"`
	RemainingQuota  *int      `json:"remainingQuota,omitempty"`
	AllowedModels   []string  `json:"allowedModels,omitempty"`
	ExcludedModels  []string  `json:"excludedModels,omitempty"`
	UpstreamBaseURL string    `json:"upstreamBaseUrl,omitempty"`
	UpstreamAPIKey  string    `json:"upstreamApiKey,omitempty"`
	WireAPI         string    `json:"wireApi,omitempty"`
	CreatedAt       time.Time `json:"createdAt"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type cooldown struct {
	ModelID     string    `json:"modelId"`
	NextRetryAt time.Time `json:"nextRetryAt"`
	Reason      string    `json:"reason"`
}

type stickySession struct {
	Key           string    `json:"key"`
	ModelID       string    `json:"modelId"`
	AccountID     string    `json:"accountId"`
	CreatedAt     time.Time `json:"createdAt"`
	LastSuccessAt time.Time `json:"lastSuccessAt"`
	FailoverFrom  string    `json:"failoverFrom,omitempty"`
}

type accountHealth struct {
	LastSuccessAt      time.Time `json:"lastSuccessAt,omitempty"`
	LastFailureAt      time.Time `json:"lastFailureAt,omitempty"`
	LastFailureReason  string    `json:"lastFailureReason,omitempty"`
	ConsecutiveFailure int       `json:"consecutiveFailure"`
}

type state struct {
	StickySessions map[string]stickySession `json:"stickySessions"`
	Cooldowns      map[string][]cooldown    `json:"cooldowns"`
	Health         map[string]accountHealth `json:"health"`
	RequestCount   uint64                   `json:"requestCount"`
	SuccessCount   uint64                   `json:"successCount"`
	FailureCount   uint64                   `json:"failureCount"`
	UpdatedAt      time.Time                `json:"updatedAt"`
}

type app struct {
	mu               sync.RWMutex
	config           config
	state            state
	dataDir          string
	apiKeys          [][]byte
	adminUser        string
	adminHash        []byte
	sessionKey       []byte
	publicAddress    string
	adminAddress     string
	allowRemoteAdmin bool
	client           *http.Client
	logger           *log.Logger
}

func main() {
	if len(os.Args) > 1 && os.Args[1] == "hash-password" {
		password := os.Getenv("CODEX_POOL_ADMIN_PASSWORD")
		if password == "" {
			log.Fatal("CODEX_POOL_ADMIN_PASSWORD is required for hash-password")
		}
		hash, err := newPasswordHash(password)
		if err != nil {
			log.Fatalf("generate password hash: %v", err)
		}
		fmt.Println(hash)
		return
	}

	a, err := newAppFromEnv()
	if err != nil {
		log.Fatal(err)
	}
	if err := a.serve(); err != nil {
		log.Fatal(err)
	}
}

func newAppFromEnv() (*app, error) {
	keys, err := loadAPIKeys()
	if err != nil {
		return nil, err
	}
	adminHash := os.Getenv("CODEX_POOL_ADMIN_PASSWORD_HASH")
	if adminHash == "" {
		return nil, errors.New("CODEX_POOL_ADMIN_PASSWORD_HASH is required")
	}
	if !validPasswordHash(adminHash) {
		return nil, errors.New("CODEX_POOL_ADMIN_PASSWORD_HASH must be a valid pbkdf2-sha256 hash generated by hash-password")
	}
	publicAddress := envOr("CODEX_POOL_PUBLIC_ADDR", publicAddressDefault)
	adminAddress := envOr("CODEX_POOL_ADMIN_ADDR", adminAddressDefault)
	allowRemote := os.Getenv("CODEX_POOL_ALLOW_REMOTE_ADMIN") == "true"
	if !allowRemote && !isLoopbackAddress(adminAddress) {
		return nil, errors.New("admin address must be loopback unless CODEX_POOL_ALLOW_REMOTE_ADMIN=true")
	}

	key := make([]byte, 32)
	if _, err := rand.Read(key); err != nil {
		return nil, fmt.Errorf("generate session key: %w", err)
	}
	a := &app{
		dataDir:          envOr("CODEX_POOL_DATA_DIR", "/data"),
		apiKeys:          keys,
		adminUser:        envOr("CODEX_POOL_ADMIN_USERNAME", "admin"),
		adminHash:        []byte(adminHash),
		sessionKey:       key,
		publicAddress:    publicAddress,
		adminAddress:     adminAddress,
		allowRemoteAdmin: allowRemote,
		client:           &http.Client{Timeout: 5 * time.Minute},
		logger:           log.New(os.Stdout, "codex-pool ", log.LstdFlags|log.LUTC),
	}
	if err := a.load(); err != nil {
		return nil, err
	}
	return a, nil
}

func (a *app) load() error {
	if err := os.MkdirAll(filepath.Join(a.dataDir, "state"), 0o700); err != nil {
		return fmt.Errorf("create data directory: %w", err)
	}
	a.config = config{DefaultModel: envOr("CODEX_POOL_DEFAULT_MODEL", "gpt-5.4"), ModelAliases: map[string]string{}}
	a.state = state{StickySessions: map[string]stickySession{}, Cooldowns: map[string][]cooldown{}, Health: map[string]accountHealth{}}
	if err := readJSON(filepath.Join(a.dataDir, "config.json"), &a.config); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read config: %w", err)
	}
	if err := readJSON(filepath.Join(a.dataDir, "state", "runtime.json"), &a.state); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("read runtime state: %w", err)
	}
	if a.config.ModelAliases == nil {
		a.config.ModelAliases = map[string]string{}
	}
	if a.state.StickySessions == nil {
		a.state.StickySessions = map[string]stickySession{}
	}
	if a.state.Cooldowns == nil {
		a.state.Cooldowns = map[string][]cooldown{}
	}
	if a.state.Health == nil {
		a.state.Health = map[string]accountHealth{}
	}
	if len(a.config.Accounts) == 0 && os.Getenv("CODEX_POOL_UPSTREAM_BASE_URL") != "" {
		now := time.Now().UTC()
		a.config.Accounts = []account{{
			ID:              "provider-default",
			Label:           "Default provider",
			AuthType:        "provider_api_key",
			Enabled:         true,
			InPool:          true,
			Priority:        100,
			UpstreamBaseURL: strings.TrimRight(os.Getenv("CODEX_POOL_UPSTREAM_BASE_URL"), "/"),
			UpstreamAPIKey:  os.Getenv("CODEX_POOL_UPSTREAM_API_KEY"),
			WireAPI:         normalWireAPI(os.Getenv("CODEX_POOL_UPSTREAM_WIRE_API")),
			CreatedAt:       now,
			UpdatedAt:       now,
		}}
		a.config.CreatedAt = now
		if err := a.saveLocked(); err != nil {
			return err
		}
	}
	return nil
}

func (a *app) serve() error {
	public := &http.Server{Addr: a.publicAddress, Handler: a.publicMux(), ReadHeaderTimeout: 10 * time.Second}
	admin := &http.Server{Addr: a.adminAddress, Handler: a.adminMux(), ReadHeaderTimeout: 10 * time.Second}
	publicListener, err := net.Listen("tcp", a.publicAddress)
	if err != nil {
		return fmt.Errorf("listen public API: %w", err)
	}
	adminListener, err := net.Listen("tcp", a.adminAddress)
	if err != nil {
		_ = publicListener.Close()
		return fmt.Errorf("listen admin API: %w", err)
	}
	a.logger.Printf("public API listening on %s; admin listening on %s", a.publicAddress, a.adminAddress)
	errCh := make(chan error, 2)
	go func() { errCh <- public.Serve(publicListener) }()
	go func() { errCh <- admin.Serve(adminListener) }()
	err = <-errCh
	if errors.Is(err, http.ErrServerClosed) {
		return nil
	}
	return err
}

func (a *app) publicMux() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /healthz", a.handleHealthz)
	mux.HandleFunc("GET /v1/models", a.requireAPIKey(a.handleModels))
	mux.HandleFunc("POST /v1/responses", a.requireAPIKey(a.handleResponses))
	mux.HandleFunc("POST /v1/responses/compact", a.requireAPIKey(a.handleResponses))
	mux.HandleFunc("POST /v1/chat/completions", a.requireAPIKey(a.handleChatCompletions))
	return recovery(mux)
}

func (a *app) adminMux() http.Handler {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /admin", a.handleAdminPage)
	mux.HandleFunc("GET /admin/assets/app.css", handleAdminCSS)
	mux.HandleFunc("GET /admin/assets/app.js", handleAdminJS)
	mux.HandleFunc("POST /admin/api/login", a.handleAdminLogin)
	mux.HandleFunc("POST /admin/api/logout", a.requireAdmin(a.handleAdminLogout))
	mux.HandleFunc("GET /admin/api/state", a.requireAdmin(a.handleAdminState))
	mux.HandleFunc("GET /admin/api/accounts", a.requireAdmin(a.handleAccounts))
	mux.HandleFunc("POST /admin/api/accounts", a.requireAdmin(a.handleAccounts))
	mux.HandleFunc("GET /admin/api/accounts/health", a.requireAdmin(a.handleAccountHealth))
	mux.HandleFunc("POST /admin/api/accounts/quota/refresh-all", a.requireAdmin(a.handleRefreshAllQuota))
	mux.HandleFunc("GET /admin/api/sticky-sessions", a.requireAdmin(a.handleStickySessions))
	mux.HandleFunc("DELETE /admin/api/sticky-sessions/", a.requireAdmin(a.handleStickySessionDelete))
	mux.HandleFunc("POST /admin/api/accounts/", a.requireAdmin(a.handleAccountAction))
	mux.HandleFunc("DELETE /admin/api/accounts/", a.requireAdmin(a.handleAccountDelete))
	return recovery(mux)
}

func (a *app) handleHealthz(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

func (a *app) handleModels(w http.ResponseWriter, r *http.Request) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	models := a.modelsLocked()
	if r.URL.Query().Get("client_version") != "" {
		items := make([]map[string]any, 0, len(models))
		for _, model := range models {
			items = append(items, map[string]any{"id": model, "slug": model, "display_name": model, "description": model, "context_length": 272000, "max_context_window": 272000, "priority": 1000, "additional_speed_tiers": []any{}, "service_tiers": []any{}})
		}
		writeJSON(w, http.StatusOK, map[string]any{"models": items})
		return
	}
	items := make([]map[string]any, 0, len(models))
	for _, model := range models {
		items = append(items, map[string]any{"id": model, "object": "model", "created": 0, "owned_by": "codex-pool"})
	}
	writeJSON(w, http.StatusOK, map[string]any{"object": "list", "data": items})
}

func (a *app) handleResponses(w http.ResponseWriter, r *http.Request) {
	a.handleProxy(w, r, false)
}

func (a *app) handleChatCompletions(w http.ResponseWriter, r *http.Request) {
	a.handleProxy(w, r, true)
}

func (a *app) handleProxy(w http.ResponseWriter, r *http.Request, chat bool) {
	body, err := io.ReadAll(io.LimitReader(r.Body, maxRequestBody+1))
	if err != nil || len(body) > maxRequestBody {
		writeOpenAIError(w, http.StatusBadRequest, "invalid_request", "request body is invalid or too large")
		return
	}
	var payload map[string]any
	if err := json.Unmarshal(body, &payload); err != nil {
		writeOpenAIError(w, http.StatusBadRequest, "invalid_request", "request body must be JSON")
		return
	}
	requestedModel, _ := payload["model"].(string)
	a.mu.RLock()
	defaultModel := a.config.DefaultModel
	a.mu.RUnlock()
	if requestedModel == "" {
		requestedModel = defaultModel
	}
	model, tier := parseModel(requestedModel)
	a.mu.RLock()
	if alias, ok := a.config.ModelAliases[model]; ok {
		model = alias
	}
	a.mu.RUnlock()
	payload["model"] = model
	if !chat && tier != "" && tier != "none" {
		payload["reasoning"] = map[string]any{"effort": tier}
	}
	updatedBody, err := json.Marshal(payload)
	if err != nil {
		writeOpenAIError(w, http.StatusBadRequest, "invalid_request", "unable to encode request")
		return
	}
	stickyKey := a.stickyKey(r, payload, model)
	excluded := map[string]bool{}
	for attempt := 0; attempt < 3; attempt++ {
		candidate, err := a.selectAccount(stickyKey, model, excluded)
		if err != nil {
			writeOpenAIError(w, http.StatusServiceUnavailable, "all_accounts_cooling_down", err.Error())
			return
		}
		endpoint, outBody, convertResponse, err := prepareUpstreamRequest(candidate, updatedBody, chat)
		if err != nil {
			writeOpenAIError(w, http.StatusBadGateway, "bad_gateway", err.Error())
			return
		}
		response, err := a.forward(r.Context(), candidate, endpoint, outBody, r.Header.Get("Accept"))
		if err != nil {
			excluded[candidate.ID] = true
			a.markFailure(candidate.ID, model, "upstream_transport_error", 30*time.Second)
			continue
		}
		if response.StatusCode == http.StatusTooManyRequests || response.StatusCode >= http.StatusInternalServerError {
			_ = response.Body.Close()
			excluded[candidate.ID] = true
			wait := retryAfter(response.Header.Get("Retry-After"))
			reason := "upstream_5xx"
			if response.StatusCode == http.StatusTooManyRequests {
				reason = "rate_limited"
			}
			a.markFailure(candidate.ID, model, reason, wait)
			continue
		}
		defer response.Body.Close()
		if convertResponse {
			a.writeChatFromResponse(w, response, model)
		} else {
			copyProxyResponse(w, response)
		}
		a.markSuccess(stickyKey, model, candidate.ID)
		return
	}
	writeOpenAIError(w, http.StatusBadGateway, "bad_gateway", "all eligible upstream accounts failed")
}

func prepareUpstreamRequest(candidate account, body []byte, chat bool) (string, []byte, bool, error) {
	base := strings.TrimRight(candidate.UpstreamBaseURL, "/")
	if base == "" {
		return "", nil, false, errors.New("selected account has no upstreamBaseUrl")
	}
	if !chat || normalWireAPI(candidate.WireAPI) == "chat_completions" {
		path := "/responses"
		if chat {
			path = "/chat/completions"
		}
		return base + path, body, false, nil
	}
	var chatRequest map[string]any
	if err := json.Unmarshal(body, &chatRequest); err != nil {
		return "", nil, false, err
	}
	input := make([]map[string]any, 0)
	if messages, ok := chatRequest["messages"].([]any); ok {
		for _, raw := range messages {
			message, _ := raw.(map[string]any)
			input = append(input, map[string]any{"role": message["role"], "content": message["content"]})
		}
	}
	responsesRequest := map[string]any{"model": chatRequest["model"], "input": input}
	if stream, _ := chatRequest["stream"].(bool); stream {
		responsesRequest["stream"] = true
	}
	converted, err := json.Marshal(responsesRequest)
	return base + "/responses", converted, true, err
}

func (a *app) forward(ctx context.Context, candidate account, endpoint string, body []byte, accept string) (*http.Response, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodPost, endpoint, strings.NewReader(string(body)))
	if err != nil {
		return nil, err
	}
	req.Header.Set("Content-Type", "application/json")
	if accept != "" {
		req.Header.Set("Accept", accept)
	}
	if candidate.UpstreamAPIKey != "" {
		req.Header.Set("Authorization", "Bearer "+candidate.UpstreamAPIKey)
	}
	return a.client.Do(req)
}

func (a *app) writeChatFromResponse(w http.ResponseWriter, response *http.Response, model string) {
	if response.StatusCode < 200 || response.StatusCode > 299 {
		copyProxyResponse(w, response)
		return
	}
	var data map[string]any
	if err := json.NewDecoder(response.Body).Decode(&data); err != nil {
		writeOpenAIError(w, http.StatusBadGateway, "bad_gateway", "invalid Responses API payload from upstream")
		return
	}
	text := outputText(data)
	created := time.Now().Unix()
	writeJSON(w, http.StatusOK, map[string]any{
		"id": "chatcmpl_" + randomID(), "object": "chat.completion", "created": created, "model": model,
		"choices": []map[string]any{{"index": 0, "message": map[string]any{"role": "assistant", "content": text}, "finish_reason": "stop"}},
	})
}

func outputText(data map[string]any) string {
	output, _ := data["output"].([]any)
	for _, raw := range output {
		item, _ := raw.(map[string]any)
		content, _ := item["content"].([]any)
		for _, c := range content {
			part, _ := c.(map[string]any)
			if text, ok := part["text"].(string); ok {
				return text
			}
		}
	}
	return ""
}

func copyProxyResponse(w http.ResponseWriter, response *http.Response) {
	for _, header := range []string{"Content-Type", "Cache-Control", "X-Request-Id"} {
		if value := response.Header.Get(header); value != "" {
			w.Header().Set(header, value)
		}
	}
	w.WriteHeader(response.StatusCode)
	_, _ = io.Copy(w, response.Body)
}

func (a *app) handleAdminPage(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Content-Security-Policy", "default-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'self'")
	_, _ = io.WriteString(w, adminPageHTML)
}

func (a *app) handleAdminLogin(w http.ResponseWriter, r *http.Request) {
	var request struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
	if err := json.NewDecoder(io.LimitReader(r.Body, 4096)).Decode(&request); err != nil || request.Username != a.adminUser || !verifyPasswordHash(string(a.adminHash), request.Password) {
		writeOpenAIError(w, http.StatusUnauthorized, "invalid_admin_credentials", "invalid username or password")
		return
	}
	expires := time.Now().UTC().Add(sessionLifetime)
	token := a.signSession(a.adminUser, expires)
	csrf := randomID()
	http.SetCookie(w, &http.Cookie{Name: "codex_pool_session", Value: token, Path: "/admin", HttpOnly: true, SameSite: http.SameSiteStrictMode, Secure: r.TLS != nil, Expires: expires})
	http.SetCookie(w, &http.Cookie{Name: "codex_pool_csrf", Value: csrf, Path: "/admin", HttpOnly: false, SameSite: http.SameSiteStrictMode, Secure: r.TLS != nil, Expires: expires})
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "csrfToken": csrf})
}

func (a *app) handleAdminLogout(w http.ResponseWriter, _ *http.Request) {
	http.SetCookie(w, &http.Cookie{Name: "codex_pool_session", Value: "", Path: "/admin", MaxAge: -1, HttpOnly: true})
	http.SetCookie(w, &http.Cookie{Name: "codex_pool_csrf", Value: "", Path: "/admin", MaxAge: -1})
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

func (a *app) handleAdminState(w http.ResponseWriter, _ *http.Request) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "state": map[string]any{"running": true, "routingStrategy": "sticky_failover", "defaultModel": a.config.DefaultModel, "accounts": publicAccounts(a.config.Accounts), "requestCount": a.state.RequestCount, "successCount": a.state.SuccessCount, "failureCount": a.state.FailureCount, "summary": a.dashboardSummaryLocked(time.Now().UTC())}})
}

func (a *app) handleAccounts(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodGet {
		a.mu.RLock()
		defer a.mu.RUnlock()
		writeJSON(w, http.StatusOK, map[string]any{"ok": true, "accounts": publicAccounts(a.config.Accounts)})
		return
	}
	var input account
	if err := json.NewDecoder(io.LimitReader(r.Body, maxRequestBody)).Decode(&input); err != nil {
		writeOpenAIError(w, http.StatusBadRequest, "invalid_request", "invalid account JSON")
		return
	}
	if !validAccountID(input.ID) || strings.TrimSpace(input.UpstreamBaseURL) == "" {
		writeOpenAIError(w, http.StatusBadRequest, "invalid_request", "id and upstreamBaseUrl are required")
		return
	}
	input.UpstreamBaseURL = strings.TrimRight(input.UpstreamBaseURL, "/")
	input.WireAPI = normalWireAPI(input.WireAPI)
	if input.AuthType == "" {
		input.AuthType = "provider_api_key"
	}
	now := time.Now().UTC()
	input.CreatedAt = now
	input.UpdatedAt = now
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.accountLocked(input.ID) != nil {
		writeOpenAIError(w, http.StatusConflict, "account_exists", "account id already exists")
		return
	}
	a.config.Accounts = append(a.config.Accounts, input)
	if err := a.saveLocked(); err != nil {
		writeOpenAIError(w, http.StatusInternalServerError, "storage_error", "unable to persist account")
		return
	}
	writeJSON(w, http.StatusCreated, map[string]any{"ok": true, "account": publicAccount(input)})
}

func (a *app) handleAccountHealth(w http.ResponseWriter, _ *http.Request) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	items := make([]map[string]any, 0, len(a.config.Accounts))
	now := time.Now().UTC()
	for _, account := range a.config.Accounts {
		items = append(items, a.accountHealthItemLocked(account, now))
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "accounts": items})
}

func (a *app) handleRefreshAllQuota(w http.ResponseWriter, _ *http.Request) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	results := make([]map[string]any, 0, len(a.config.Accounts))
	for _, account := range a.config.Accounts {
		results = append(results, map[string]any{"accountId": account.ID, "ok": true, "quota": nil, "message": "provider API accounts do not expose a common quota endpoint"})
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "results": results})
}

func (a *app) handleStickySessions(w http.ResponseWriter, _ *http.Request) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	items := make([]stickySession, 0, len(a.state.StickySessions))
	for _, item := range a.state.StickySessions {
		items = append(items, item)
	}
	sort.Slice(items, func(i, j int) bool { return items[i].Key < items[j].Key })
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "sessions": items})
}

func (a *app) handleStickySessionDelete(w http.ResponseWriter, r *http.Request) {
	key := strings.TrimPrefix(r.URL.Path, "/admin/api/sticky-sessions/")
	if key == "" {
		writeOpenAIError(w, http.StatusBadRequest, "invalid_request", "session key is required")
		return
	}
	a.mu.Lock()
	defer a.mu.Unlock()
	delete(a.state.StickySessions, key)
	if err := a.saveLocked(); err != nil {
		writeOpenAIError(w, 500, "storage_error", "unable to persist state")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true})
}

func (a *app) handleAccountAction(w http.ResponseWriter, r *http.Request) {
	parts := strings.Split(strings.TrimPrefix(r.URL.Path, "/admin/api/accounts/"), "/")
	if len(parts) < 2 {
		writeOpenAIError(w, 404, "not_found", "account action not found")
		return
	}
	id, action := parts[0], strings.Join(parts[1:], "/")
	a.mu.Lock()
	defer a.mu.Unlock()
	item := a.accountLocked(id)
	if item == nil {
		writeOpenAIError(w, 404, "not_found", "account not found")
		return
	}
	switch action {
	case "enable":
		item.Enabled = true
	case "disable":
		item.Enabled = false
		item.InPool = false
		a.clearStickyForAccountLocked(id)
	case "pool-add":
		item.InPool = true
	case "pool-remove":
		item.InPool = false
		a.clearStickyForAccountLocked(id)
	case "cooldowns/clear":
		delete(a.state.Cooldowns, id)
	case "quota/set":
		var request struct {
			RemainingQuota *int `json:"remainingQuota"`
		}
		if err := json.NewDecoder(io.LimitReader(r.Body, 4096)).Decode(&request); err != nil || request.RemainingQuota == nil || *request.RemainingQuota < 0 || *request.RemainingQuota > 100 {
			writeOpenAIError(w, http.StatusBadRequest, "invalid_request", "remainingQuota must be an integer from 0 to 100")
			return
		}
		item.RemainingQuota = request.RemainingQuota
	case "quota/refresh":
		writeJSON(w, http.StatusOK, map[string]any{"ok": true, "accountId": id, "quota": nil, "message": "provider API accounts do not expose a common quota endpoint"})
		return
	default:
		writeOpenAIError(w, 404, "not_found", "account action not found")
		return
	}
	item.UpdatedAt = time.Now().UTC()
	if err := a.saveLocked(); err != nil {
		writeOpenAIError(w, 500, "storage_error", "unable to persist account")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"ok": true, "account": publicAccount(*item)})
}

func (a *app) handleAccountDelete(w http.ResponseWriter, r *http.Request) {
	id := strings.TrimPrefix(r.URL.Path, "/admin/api/accounts/")
	a.mu.Lock()
	defer a.mu.Unlock()
	for i, account := range a.config.Accounts {
		if account.ID == id {
			a.config.Accounts = append(a.config.Accounts[:i], a.config.Accounts[i+1:]...)
			delete(a.state.Cooldowns, id)
			a.clearStickyForAccountLocked(id)
			if err := a.saveLocked(); err != nil {
				writeOpenAIError(w, 500, "storage_error", "unable to persist account")
				return
			}
			writeJSON(w, http.StatusOK, map[string]any{"ok": true})
			return
		}
	}
	writeOpenAIError(w, 404, "not_found", "account not found")
}

func (a *app) requireAPIKey(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if !a.validAPIKey(requestAPIKey(r)) {
			writeOpenAIError(w, http.StatusUnauthorized, "invalid_api_key", "invalid or missing API key")
			return
		}
		next(w, r)
	}
}

func (a *app) requireAdmin(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		cookie, err := r.Cookie("codex_pool_session")
		if err != nil || !a.validSession(cookie.Value) {
			writeOpenAIError(w, http.StatusUnauthorized, "admin_unauthorized", "admin login required")
			return
		}
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			csrfCookie, err := r.Cookie("codex_pool_csrf")
			if err != nil || csrfCookie.Value == "" || subtle.ConstantTimeCompare([]byte(csrfCookie.Value), []byte(r.Header.Get("X-CSRF-Token"))) != 1 {
				writeOpenAIError(w, http.StatusForbidden, "csrf_invalid", "valid CSRF token required")
				return
			}
		}
		next(w, r)
	}
}

func (a *app) validAPIKey(value string) bool {
	if value == "" {
		return false
	}
	for _, key := range a.apiKeys {
		if subtle.ConstantTimeCompare([]byte(value), key) == 1 {
			return true
		}
	}
	return false
}

func requestAPIKey(r *http.Request) string {
	for _, value := range []string{r.Header.Get("Authorization"), r.Header.Get("X-Goog-Api-Key"), r.Header.Get("X-Api-Key"), r.URL.Query().Get("key"), r.URL.Query().Get("auth_token")} {
		if strings.HasPrefix(value, "Bearer ") {
			value = strings.TrimSpace(strings.TrimPrefix(value, "Bearer "))
		}
		if value != "" {
			return value
		}
	}
	return ""
}

func (a *app) signSession(user string, expires time.Time) string {
	payload := user + "|" + strconv.FormatInt(expires.Unix(), 10)
	mac := hmac.New(sha256.New, a.sessionKey)
	_, _ = mac.Write([]byte(payload))
	return base64.RawURLEncoding.EncodeToString([]byte(payload + "|" + base64.RawURLEncoding.EncodeToString(mac.Sum(nil))))
}

func (a *app) validSession(token string) bool {
	decoded, err := base64.RawURLEncoding.DecodeString(token)
	if err != nil {
		return false
	}
	parts := strings.Split(string(decoded), "|")
	if len(parts) != 3 || parts[0] != a.adminUser {
		return false
	}
	expiry, err := strconv.ParseInt(parts[1], 10, 64)
	if err != nil || time.Now().After(time.Unix(expiry, 0)) {
		return false
	}
	expected := a.signSession(parts[0], time.Unix(expiry, 0))
	return subtle.ConstantTimeCompare([]byte(token), []byte(expected)) == 1
}

func (a *app) modelsLocked() []string {
	set := map[string]bool{a.config.DefaultModel: true}
	for _, account := range a.config.Accounts {
		for _, model := range account.AllowedModels {
			set[model] = true
		}
	}
	for alias := range a.config.ModelAliases {
		set[alias] = true
	}
	models := make([]string, 0, len(set))
	for model := range set {
		if model != "" {
			models = append(models, model)
		}
	}
	sort.Strings(models)
	return models
}

func (a *app) selectAccount(stickyKey, model string, excluded map[string]bool) (account, error) {
	a.mu.Lock()
	defer a.mu.Unlock()
	now := time.Now().UTC()
	if existing, ok := a.state.StickySessions[stickyKey]; ok && !excluded[existing.AccountID] {
		if item := a.accountLocked(existing.AccountID); item != nil && a.usableLocked(*item, model, now) {
			return *item, nil
		}
	}
	eligible := make([]account, 0)
	for _, item := range a.config.Accounts {
		if !excluded[item.ID] && a.usableLocked(item, model, now) {
			eligible = append(eligible, item)
		}
	}
	if len(eligible) == 0 {
		return account{}, errors.New("no eligible account is available for the requested model")
	}
	sort.SliceStable(eligible, func(i, j int) bool {
		if eligible[i].Priority == eligible[j].Priority {
			return eligible[i].ID < eligible[j].ID
		}
		return eligible[i].Priority > eligible[j].Priority
	})
	return eligible[0], nil
}

func (a *app) usableLocked(item account, model string, now time.Time) bool {
	if !item.Enabled || !item.InPool || item.UpstreamBaseURL == "" || !allowedModel(item, model) {
		return false
	}
	for _, cd := range a.state.Cooldowns[item.ID] {
		if cd.ModelID == model && cd.NextRetryAt.After(now) {
			return false
		}
	}
	return true
}

func (a *app) markFailure(accountID, model, reason string, duration time.Duration) {
	a.mu.Lock()
	defer a.mu.Unlock()
	if a.state.Health == nil {
		a.state.Health = map[string]accountHealth{}
	}
	now := time.Now().UTC()
	health := a.state.Health[accountID]
	health.LastFailureAt = now
	health.LastFailureReason = reason
	health.ConsecutiveFailure++
	a.state.Health[accountID] = health
	a.state.FailureCount++
	a.state.Cooldowns[accountID] = append(a.state.Cooldowns[accountID], cooldown{ModelID: model, NextRetryAt: now.Add(duration), Reason: reason})
	_ = a.saveLocked()
}

func (a *app) markSuccess(key, model, accountID string) {
	a.mu.Lock()
	defer a.mu.Unlock()
	now := time.Now().UTC()
	if a.state.Health == nil {
		a.state.Health = map[string]accountHealth{}
	}
	health := a.state.Health[accountID]
	health.LastSuccessAt = now
	health.ConsecutiveFailure = 0
	a.state.Health[accountID] = health
	prior := a.state.StickySessions[key]
	a.state.StickySessions[key] = stickySession{Key: key, ModelID: model, AccountID: accountID, CreatedAt: chooseTime(prior.CreatedAt, now), LastSuccessAt: now, FailoverFrom: prior.AccountID}
	a.state.RequestCount++
	a.state.SuccessCount++
	_ = a.saveLocked()
}

func (a *app) accountLocked(id string) *account {
	for i := range a.config.Accounts {
		if a.config.Accounts[i].ID == id {
			return &a.config.Accounts[i]
		}
	}
	return nil
}
func (a *app) clearStickyForAccountLocked(id string) {
	for key, item := range a.state.StickySessions {
		if item.AccountID == id {
			delete(a.state.StickySessions, key)
		}
	}
}

func (a *app) saveLocked() error {
	a.config.UpdatedAt = time.Now().UTC()
	a.state.UpdatedAt = time.Now().UTC()
	if err := writeJSONAtomic(filepath.Join(a.dataDir, "config.json"), a.config); err != nil {
		return err
	}
	return writeJSONAtomic(filepath.Join(a.dataDir, "state", "runtime.json"), a.state)
}

func loadAPIKeys() ([][]byte, error) {
	raw := append(strings.Split(os.Getenv("CODEX_POOL_API_KEYS"), ","), os.Getenv("CODEX_POOL_API_KEY"))
	keys := make([][]byte, 0, len(raw))
	for _, value := range raw {
		if value = strings.TrimSpace(value); value != "" {
			if strings.Contains(value, "replace_with") || strings.Contains(value, "replace-with") {
				return nil, errors.New("public API key cannot use an example value")
			}
			keys = append(keys, []byte(value))
		}
	}
	if len(keys) == 0 {
		return nil, errors.New("CODEX_POOL_API_KEY or CODEX_POOL_API_KEYS is required")
	}
	return keys, nil
}

func parseModel(value string) (string, string) {
	end := strings.LastIndex(value, ")")
	start := strings.LastIndex(value, "(")
	if start > 0 && end == len(value)-1 {
		tier := value[start+1 : end]
		switch tier {
		case "none", "auto", "minimal", "low", "medium", "high", "xhigh", "max":
			return value[:start], tier
		}
	}
	return value, ""
}

func (a *app) stickyKey(r *http.Request, payload map[string]any, model string) string {
	for _, value := range []string{r.Header.Get("X-Codex-Pool-Session"), r.Header.Get("X-Codex-Pool-Project")} {
		if value != "" {
			return model + ":" + value
		}
	}
	for _, name := range []string{"prompt_cache_key", "session_id", "conversation_id", "thread_id"} {
		if value, ok := payload[name].(string); ok && value != "" {
			return model + ":" + value
		}
	}
	encoded, _ := json.Marshal(payload["input"])
	sum := sha256.Sum256(append([]byte(model+":"), encoded...))
	return model + ":" + fmt.Sprintf("%x", sum[:8])
}

func allowedModel(item account, model string) bool {
	for _, excluded := range item.ExcludedModels {
		if excluded == model {
			return false
		}
	}
	if len(item.AllowedModels) == 0 {
		return true
	}
	for _, allowed := range item.AllowedModels {
		if allowed == model {
			return true
		}
	}
	return false
}

func normalWireAPI(value string) string {
	switch strings.ToLower(value) {
	case "chat_completions", "chat-completions", "openai_chat", "openai-chat", "chat":
		return "chat_completions"
	default:
		return "responses"
	}
}
func retryAfter(value string) time.Duration {
	seconds, err := strconv.Atoi(value)
	if err == nil && seconds > 0 {
		return time.Duration(seconds) * time.Second
	}
	return time.Minute
}
func activeCooldowns(values []cooldown, now time.Time) []cooldown {
	result := make([]cooldown, 0, len(values))
	for _, item := range values {
		if item.NextRetryAt.After(now) {
			result = append(result, item)
		}
	}
	return result
}
func (a *app) dashboardSummaryLocked(now time.Time) map[string]int {
	summary := map[string]int{"total": len(a.config.Accounts), "ready": 0, "low": 0, "cooldown": 0, "error": 0}
	for _, item := range a.config.Accounts {
		status, _ := a.accountStatusLocked(item, now)
		if _, ok := summary[status]; ok {
			summary[status]++
		}
	}
	return summary
}
func (a *app) accountHealthItemLocked(item account, now time.Time) map[string]any {
	cooldowns := activeCooldowns(a.state.Cooldowns[item.ID], now)
	status, reason := a.accountStatusLocked(item, now)
	health := a.state.Health[item.ID]
	return map[string]any{"accountId": item.ID, "available": status == "ready" || status == "low", "status": status, "statusReason": reason, "cooldowns": cooldowns, "lastSuccessAt": health.LastSuccessAt, "lastFailureAt": health.LastFailureAt, "lastFailureReason": health.LastFailureReason, "consecutiveFailure": health.ConsecutiveFailure, "remainingQuota": item.RemainingQuota}
}
func (a *app) accountStatusLocked(item account, now time.Time) (string, string) {
	if !item.Enabled {
		return "disabled", "Account is disabled"
	}
	if !item.InPool {
		return "standby", "Account is not in the pool"
	}
	if cooldowns := activeCooldowns(a.state.Cooldowns[item.ID], now); len(cooldowns) > 0 {
		return "cooldown", cooldowns[0].Reason
	}
	if health := a.state.Health[item.ID]; health.ConsecutiveFailure > 0 {
		return "error", health.LastFailureReason
	}
	if item.RemainingQuota != nil && *item.RemainingQuota <= 20 {
		return "low", "Remaining quota is at or below 20%"
	}
	return "ready", "Ready"
}
func publicAccounts(values []account) []map[string]any {
	result := make([]map[string]any, 0, len(values))
	for _, item := range values {
		result = append(result, publicAccount(item))
	}
	return result
}
func publicAccount(item account) map[string]any {
	return map[string]any{"id": item.ID, "label": item.Label, "email": item.Email, "authType": item.AuthType, "enabled": item.Enabled, "inPool": item.InPool, "priority": item.Priority, "remainingQuota": item.RemainingQuota, "allowedModels": item.AllowedModels, "excludedModels": item.ExcludedModels, "upstreamBaseUrl": item.UpstreamBaseURL, "wireApi": item.WireAPI, "hasUpstreamApiKey": item.UpstreamAPIKey != ""}
}
func validAccountID(id string) bool {
	if id == "" || len(id) > 80 {
		return false
	}
	for _, c := range id {
		if !(c >= 'a' && c <= 'z' || c >= 'A' && c <= 'Z' || c >= '0' && c <= '9' || c == '-' || c == '_') {
			return false
		}
	}
	return true
}
func isLoopbackAddress(address string) bool {
	host, _, err := net.SplitHostPort(address)
	if err != nil {
		return false
	}
	if host == "localhost" {
		return true
	}
	ip := net.ParseIP(host)
	return ip != nil && ip.IsLoopback()
}
func envOr(name, fallback string) string {
	if value := os.Getenv(name); value != "" {
		return value
	}
	return fallback
}
func chooseTime(value, fallback time.Time) time.Time {
	if value.IsZero() {
		return fallback
	}
	return value
}
func randomID() string {
	value := make([]byte, 16)
	if _, err := rand.Read(value); err != nil {
		panic(err)
	}
	return base64.RawURLEncoding.EncodeToString(value)
}

// PBKDF2 is implemented locally so image builds do not depend on a host or module registry.
func newPasswordHash(password string) (string, error) {
	salt := make([]byte, 16)
	if _, err := rand.Read(salt); err != nil {
		return "", err
	}
	const iterations = 600000
	derived := pbkdf2SHA256([]byte(password), salt, iterations, 32)
	return fmt.Sprintf("pbkdf2-sha256:%d:%s:%s", iterations, base64.RawStdEncoding.EncodeToString(salt), base64.RawStdEncoding.EncodeToString(derived)), nil
}

func validPasswordHash(value string) bool {
	_, _, _, ok := parsePasswordHash(value)
	return ok
}

func verifyPasswordHash(encoded, password string) bool {
	iterations, salt, expected, ok := parsePasswordHash(encoded)
	if !ok {
		return false
	}
	actual := pbkdf2SHA256([]byte(password), salt, iterations, len(expected))
	return subtle.ConstantTimeCompare(actual, expected) == 1
}

func parsePasswordHash(value string) (int, []byte, []byte, bool) {
	parts := strings.Split(value, ":")
	if len(parts) != 4 || parts[0] != "pbkdf2-sha256" {
		return 0, nil, nil, false
	}
	iterations, err := strconv.Atoi(parts[1])
	if err != nil || iterations < 100000 || iterations > 5000000 {
		return 0, nil, nil, false
	}
	salt, saltErr := base64.RawStdEncoding.DecodeString(parts[2])
	hash, hashErr := base64.RawStdEncoding.DecodeString(parts[3])
	if saltErr != nil || hashErr != nil || len(salt) < 16 || len(hash) != 32 {
		return 0, nil, nil, false
	}
	return iterations, salt, hash, true
}

func pbkdf2SHA256(password, salt []byte, iterations, keyLength int) []byte {
	const hashLength = 32
	blocks := (keyLength + hashLength - 1) / hashLength
	derived := make([]byte, 0, blocks*hashLength)
	for block := 1; block <= blocks; block++ {
		message := make([]byte, len(salt)+4)
		copy(message, salt)
		message[len(salt)] = byte(block >> 24)
		message[len(salt)+1] = byte(block >> 16)
		message[len(salt)+2] = byte(block >> 8)
		message[len(salt)+3] = byte(block)
		mac := hmac.New(sha256.New, password)
		_, _ = mac.Write(message)
		u := mac.Sum(nil)
		result := append([]byte(nil), u...)
		for round := 1; round < iterations; round++ {
			mac = hmac.New(sha256.New, password)
			_, _ = mac.Write(u)
			u = mac.Sum(nil)
			for i := range result {
				result[i] ^= u[i]
			}
		}
		derived = append(derived, result...)
	}
	return derived[:keyLength]
}
func readJSON(path string, target any) error {
	file, err := os.Open(path)
	if err != nil {
		return err
	}
	defer file.Close()
	return json.NewDecoder(file).Decode(target)
}
func writeJSONAtomic(path string, value any) error {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	temporary := path + ".tmp"
	if err := os.WriteFile(temporary, append(data, '\n'), 0o600); err != nil {
		return err
	}
	return os.Rename(temporary, path)
}
func writeJSON(w http.ResponseWriter, status int, value any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(value)
}
func writeOpenAIError(w http.ResponseWriter, status int, code, message string) {
	writeJSON(w, status, map[string]any{"error": map[string]string{"message": message, "type": "invalid_request_error", "code": code}})
}
func recovery(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if recover() != nil {
				writeOpenAIError(w, 500, "internal_error", "internal server error")
			}
		}()
		next.ServeHTTP(w, r)
	})
}
